# Generated by Django 3.2.17 on 2023-04-15 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autores', models.TextField(blank=True, null=True, verbose_name='Autor')),
                ('titulo', models.TextField(blank=True, null=True, verbose_name='Título')),
                ('fonte_artigo', models.TextField(blank=True, null=True, verbose_name='Fonte')),
                ('palavras_chave', models.TextField(blank=True, null=True, verbose_name='Palavra chave')),
                ('resumo_artigo', models.TextField(blank=True, null=True, verbose_name='Resumo')),
                ('endereco_autores', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('instituicao_autores', models.TextField(blank=True, null=True, verbose_name='Instituição')),
                ('agencia_fomento', models.TextField(blank=True, null=True, verbose_name='Agência')),
                ('contagem_citacoes', models.PositiveIntegerField(default=1, verbose_name='Citação')),
                ('ano_publicacao', models.CharField(blank=True, max_length=10, null=True, verbose_name='Publicação')),
                ('areas_pesquisa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Área pesquisa')),
                ('registro_criado', models.DateTimeField(auto_now_add=True)),
                ('registro_atualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pesquisa',
                'verbose_name_plural': 'Pesquisas',
                'ordering': ['id'],
            },
        ),
    ]
